services:
  backend:
    image: algo-trader-backend
    restart: always
    volumes:
      - ../../backend:/algo-trader/backend
      - ../../build:/algo-trader/build
      - ../../logs:/algo-trader/logs
      - ../../keys:/algo-trader/keys
      - ../../config:/algo-trader/config
      - ../../tests:/algo-trader/tests
    ports:
      - "5000:5000"
    user: "${USER_ID}:${GROUP_ID}"
    working_dir: /
    command: bash -c "${BACKEND_CMD}"
  backend-tests:
    image: algo-trader-backend-component-tests
    volumes:
      - ../../tests:/algo-trader/tests
      - ../../scripts:/algo-trader/scripts
    ports:
      - "5001:5001"
    environment:
      PYTHONPATH: "/algo-trader"
    working_dir: /
    command: bash -c "cd /algo-trader/tests/backend && behave --no-color ${TEST_ARGUMENTS}"
    stdin_open: true
    tty: true
