networks:
  quant-trade-studio-network:
    driver: bridge

services:
  frontend:
    image: quant-trade-studio-frontend
    networks:
      - quant-trade-studio-network
    restart: always
    volumes:
      - ../../frontend:/quant-trade-studio/frontend
    ports:
      - "4200:4200"
    working_dir: /quant-trade-studio/frontend
    command: bash -c "npm install && ng serve --host 0.0.0.0"
  backend:
    image: quant-trade-studio-backend
    networks:
      - quant-trade-studio-network
    restart: always
    volumes:
      - ../../backend:/quant-trade-studio/backend
      - ../../build:/quant-trade-studio/build
      - ../../logs:/quant-trade-studio/logs
      - ../../keys:/quant-trade-studio/keys
      - ../../config:/quant-trade-studio/config
    ports:
      - "5000:5000"
    user: "${USER_ID}:${GROUP_ID}"
    working_dir: /
    command: bash -c "/quant-trade-studio/build/debug/src/QuantTradeStudio /quant-trade-studio/config/dockerDevelConfig.json"
