networks:
  algo-trader-network:
    driver: bridge

services:
  frontend:
    image: algo-trader-frontend
    networks:
      - algo-trader-network
    restart: always
    volumes:
      - ../../frontend:/algo-trader/frontend
    ports:
      - '4200:4200'
    working_dir: /algo-trader/frontend
    command: bash -c "npm install && ng serve --host 0.0.0.0"
  backend:
    image: algo-trader-backend
    networks:
      - algo-trader-network
    restart: always
    volumes:
      - ../../backend:/algo-trader/backend
      - ../../build:/algo-trader/build
      - ../../logs:/algo-trader/logs
      - ../../keys:/algo-trader/keys
      - ../../config:/algo-trader/config
    ports:
      - "5000:5000"
    user: "${USER_ID}:${GROUP_ID}"
    working_dir: /
    command: bash -c "/algo-trader/build/debug/src/AlgoTrader /algo-trader/config/dockerDevelConfig.json"
