version: '3'

services:
  backend:
    image: algo-trader-backend
    restart: always
    volumes:
      - ../../backend:/algo-trader/backend
      - ../../build:/algo-trader/build
      - ../../logs:/algo-trader/logs
      - ../../keys:/algo-trader/keys
      - ../../config:/algo-trader/config
      - ../../tests:/algo-trader/tests
    ports:
      - "5000:5000"
    working_dir: /
    command: bash -c "/algo-trader/build/debug/src/AlgoTrader /algo-trader/tests/backend/configuration.json"
  backend-tests:
    image: algo-trader-backend-tests
    volumes:
      - ../../tests:/algo-trader/tests
      - ../../scripts:/algo-trader/scripts
    ports:
      - "5001:5001"
    working_dir: /
    command: bash -c "cd /algo-trader/tests/backend && behave"
    stdin_open: true
    tty: true
